9 спринт controllers-films-users
AtamasMaria/java-filmorate pull request #1
Opened 2023-01-15 15:21 UTC by AtamasMaria

Не все тесты API проходят успешно, пока не знаю в чем дело

2023-01-16 22:13 UTC, ohelly requested changes
Привет! Отлично проделанная работа. В целом все сделано правильно, за исключением некоторых простых моментов, которые необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.

2023-01-16 22:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +package ru.yandex.practicum.filmorate.controllers;
Рекомендация: Будет правильнее пакеты именовать в единственном числе.

2023-01-16 22:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (films.containsKey(film.getId())) {
Необходимо исправить: При создании фильма происходит проверка, существует ли такой фильм, но затем, на 36 строке, мы проставляем ему новый идентификатор. Выходит, что в таком случае нет необходимости проверять, существует ли уже фильм с таким же идентификатором.

Аналогичная проблема в UserController.

2023-01-16 22:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Рекомендация: Рекомендую для идентификатором использовать классы обертки(Integer, Long), так как они могут быть null, а примитивный int - нет.

2023-01-16 22:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
Рекомендация: Аннотация ``@NotEmpty`` используется для проверок коллекций(например ArrayList), поэтому ее можно отсюда убрать. Аннотация ``@NotBlank`` в данном случае используется правильно, эта аннотация специально создана для строк и включает в себя проверку на то, что строка != null и то, что она не пустая, поэтому аннотацию ``@NonNull`` можно также убрать.

2023-01-16 22:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotEmpty
Рекомендация: В данном классе также можно убрать лишние аннотации, по аналогии с моей рекомендацией в классе Film.

2023-01-16 22:13 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void validateFilm(Film film) {
Рекомендация: Советую все же сделать валидацию с помощью аннотаций. Текущий способ рабочий, он прозрачный и хорошо видно, что именно происходит. Но в реальных кейсах данные проверки все же выполняют с помощью аннотаций. С таким подходом приходится писать меньше кода, а также уже сразу в классе-модели видно, какие проверки происходят.

2023-01-17 16:22 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (films.containsKey(film.getId())) {
Перенесла метод setId() до всех "манипуляций"

2023-01-17 16:22 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +package ru.yandex.practicum.filmorate.controllers;
Исправила)

2023-01-17 16:23 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
Исправила)

2023-01-17 16:23 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NonNull
Исправила)

2023-01-17 16:23 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotEmpty
Исправила)

2023-01-17 16:25 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private void validateFilm(Film film) {
Сделала валидацию через аннотации + написала 2 аннотации

2023-01-18 18:27 UTC, ohelly approved these changes
Привет! Отлично, исправлены все замечания, теперь все работает корректно. Работа принята, удачи в дальнейшем обучении.

Оставил одну рекомендую, которую лучше поправить.

2023-01-18 18:27 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/annotation/validator/FilmReleaseDateValidator.java
> +        return localDate.isAfter(LocalDate.of(1895, 12, 28));
Рекомендация: В данном случае следует добавить проверку на то, что дата != null, иначе если попробовать сделать запрос с параметром releaseDate равным null вылетит NullPointerException.

2023-01-21 04:33 UTC, merged