10 спринт
AtamasMaria/java-filmorate pull request #2
Opened 2023-02-01 10:18 UTC by AtamasMaria

2023-02-04 20:54 UTC, AtamasMaria commented
Страшно намаялась с этим спринтом (

2023-02-05 19:22 UTC, ohelly requested changes
Привет! Отличная работа, в целом все работает корректно. Есть пара совсем простых ошибок, которые необходимо исправить. Также я оставил ряд рекомендаций, на которые стоит обратить внимание.

2023-02-05 19:22 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (films.containsKey(film.getId())) {
Рекомендация: Обычно для добавления нет проверки на существующий идентификатор, так как он все равно проставляется на следующий(++id). Поэтому, можно игнорировать идентификатор в пришедшем теле для добавления и просто проставлять следующий.

Справедливо и для UserStorage

2023-02-05 19:22 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (users.containsKey(user)) {
Необходимо исправить: Элемент в мапе необходимо искать по идентификатору: ``users.containsKey(user.getId());``

2023-02-05 19:22 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserStorage userStorage;
Рекомендация: Обычно, в класс-сервис инжектится только "своё" хранилище, то есть filmStorage, а вот к userStorage лучше обращаться через UserService, который в свою очередь обращается к "своему" хранилищу. Таким образом, класс-сервис является единой точкой доступа, к которой все обращаются и если поменяется бизнес логика, то она применится ко всем, кто использует этот сервис. Если возникнет вопрос "Почему нельзя использовать хранилище напрямую, если поменяется в нем, то поменяется везде?", то ответ прост - в классах хранилищах не пишут бизнес логику. На практике классы-хранилища это репозитории, которые обращаются к базе данных, они просто достают необходимый набор данных, которые уже в свою очередь обрабатываются на стороне класса-сервиса.

2023-02-05 19:22 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ExceptionHandler({FilmNotFoundException.class, UserNotFoundException.class})
Необходимо исправить: В InMemoryFilmStorage выкидывается еще просто NotFoundException, которое здесь не обрабатывается. Можно даже объединить все 3 исключения в одно - NotFoundExceptionю

2023-02-05 19:22 UTC, ohelly commented
> Страшно намаялась с этим спринтом (

а с чем конкретно возникли сложности?

2023-02-06 06:27 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final UserStorage userStorage;
Исправила)

2023-02-06 06:31 UTC, AtamasMaria commented
Сложности возникли по сути с моей невнимательностью, в классах контроллерах я сделала неправильные параметры в методах и запросы не правильно обрабатывались, поэтому половина тестов вылетало(( а я все нервы истратила меняя логику приложения(

2023-02-06 06:45 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (films.containsKey(film.getId())) {
Убрала проверку

2023-02-06 06:45 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (users.containsKey(user)) {
Исправила

2023-02-06 06:53 UTC, AtamasMaria commented
еще произошел конфликт слияния, решилось конечно быстро, но тоже немного добавило возни

2023-02-06 18:21 UTC, ohelly approved these changes
Привет! Теперь все супер, все исправлено, работа принята. Удачи в дальнейшем обучении!

По поводу того, что были сделаны неправильные параметры в классах контроллерах, что отняло много времени - советую писать тесты самостоятельно, что позволит отслеживать ошибки, тем более, что тесты были написаны в прошлом спринте и их можно было оставить, так как по сути функционал не изменился, а только добавились новые методы и если бы в коде произошли критические изменения тесты бы это показали.

Также по поводу конфликта слияния - обычно это нормальная практика и умение их решать очень пригодится, но вообще, в данном случае конфликты не должны были случится, так как разработкой спринта занимается только один человек, возможно были произведены лишние действия. Как все должно было быть:
1) в 9 спринте, создается новая ветка от ветки main, после того, как спринт завершен она сливается с помощью команды merge в ветку main.
2) в 10 спринте, от ветки мейн(которая уже содержит код из 9 спринта) также отбивается новая ветка, в котором он выполняется. После выполнения сливается обратно в main.
3) и так далее по кругу.
Можно дополнительно ознакомиться с git flow, где показан и объяснен процесс разработки приложения со стороны гита.

2023-02-08 10:41 UTC, merged