Add database
AtamasMaria/java-filmorate pull request #6
Opened 2023-03-04 08:26 UTC by AtamasMaria

2023-03-04 14:55 UTC, AtamasMaria commented
Этот спринт высосал из меня все силы(

2023-03-05 12:23 UTC, ohelly requested changes
Привет! Видно, что проделана большая работа, в целом все выполнено правильно. Есть замечания связанные в основном с оптимизацией sql запросов. Также я оставил ряд рекомендаций на которые стоит обратить внимание.

Также есть замечание: Необходимо написать тесты, по ТЗ они обязательны.

2023-03-05 12:23 UTC, ohelly commented on src/main/resources/schema.sql
> +CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
Рекомендация: mpa_id уже установлен как Primary key на 20 строке, поэтому здесь, на 23 строке, это писать необязательно, либо можно здесь оставить, а на 20 строке убрать.

Аналогично в таблице users

2023-03-05 12:23 UTC, ohelly commented on src/main/resources/schema.sql
> +ALTER TABLE film_genres ADD CONSTRAINT IF NOT EXISTS UC_GenreLine_GenreID_FilmID UNIQUE (genre_id, film_id);
Рекомендация: Для таблицы лайков тоже можно создать такой же констрейнт.

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int rate;
А что это за поле?(rate)

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!existLike.next()) {
Рекомендация: Можно убрать добавление лайков при добавлении/обновлении фильма, по ТЗ такой функциональности может и не быть. Для этого есть метод добавления лайка.

Также если добавить констрейнт в БД на уникальность лайка по полям user_id и film_id, то необходимость делать проверку на существование лайка отпадет, можно будет делать инсерт вместе с ON CONFLICT DO NOTHING, так, как сделано в GenreDbStorage.

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet sqlRowSet = jdbcTemplate.queryForRowSet(sql, userId, filmId);
Рекомендация: Можно также убрать данный запрос на 155 строке, так как он нужен только для того, чтобы потом вывести в лог, получается что лишняя нагрузка на БД.

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                new Film(
Рекомендация: Данное преобразование можно вынести в отдельный метод, так как оно дублируется здесь и в getFilmById

![image](https://user-images.githubusercontent.com/51891976/222956846-638d748c-b6a4-4c3c-a94f-f145e064a758.png)

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                        (List<Genre>) genreService.getFilmGenres(rs.getInt("film_id")),
Необходимо исправить: Необходимо вынести получение жанров в FilmService, то есть из него вызывать метод получения жанров, либо оставить здесь, но получать жанры только после того, как получены все фильмы. Сейчас объясню почему:
Сейчас на получение N фильмов выполняется N запросов на получение жанров, что не очень хорошо, так как нагружается БД, это необходимо делать одним запросом, независимо от того, сколько фильмов нам необходимо обогатить жанрами.
Итого: в GenreDbStorage должен быть метод, который одним запросом получает все жанры для всех необходимых фильмов. Для этого поможет оператор IN в запросе.

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmsPopular(Integer count) {
Необходимо исправить: Давай переработаем метод получения популярных фильмов. Сейчас в худшем случае выполняется очень много запросов - 101 строка, 102 и затем еще несколько на 111 строке. Все это можно сделать одним запросом:
В текущей реализации мы достаем сначала все идентификаторы, подходящие под наше условие(98 строка), затем, для каждого из этих идентификаторов мы достаем фильм(102строка), но нам нет необходимости это делать, ведь мы можем сразу достать все фильмы, а не только их идентификаторы:
![image](https://user-images.githubusercontent.com/51891976/222958578-89f05a46-567b-466c-9f1d-f0f692596c4f.png)

Добавим join для mpa_rating:
![image](https://user-images.githubusercontent.com/51891976/222958649-792058c9-9d29-44f3-9625-e57631a1106e.png)

Далее, я так понимаю, идет добавление фильмов в результирующий список, чтобы подбить их под количество заданное запросом(count), добавляем те фильмы, у которых нет лайков. Но мы также это можем сделать одним запросом с помощью LEFT JOIN:
![image](https://user-images.githubusercontent.com/51891976/222958759-0a3fa245-8992-430c-8fcb-9652f394bede.png)

LEFT JOIN вернет нам все результаты левой таблицы(films) попадающие под условие и все лайки, которые удалось сджойнить.

![image](https://user-images.githubusercontent.com/51891976/222958844-cf6c4dd7-cdf2-4456-a255-a0bd8c01cf6a.png)

Итого получилось следующее, мы одним запросом, достали все необходимые нам фильмы.

Подсказка по join'ам https://learndb.ru/articles/article/30

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        for (Genre genre : genres) {
Рекомендация: У jdbcTemplate есть метод batchUpdate, который позволяет сделать обновление данных одним запросом, чтобы не нагружать нашу БД несколькими запроса, как происходит сейчас.
https://mkyong.com/spring/spring-jdbctemplate-batchupdate-example/

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/mpa/MpaDbStorage.java
> +        SqlRowSet rows = jdbcTemplate.queryForRowSet("SELECT * FROM mpa WHERE mpa_id=?", mpaId);
Рекомендация: Рекомендую также переделать данный метод. Сейчас происходит 2 одинаковых запроса, если mpa в базе есть, что не есть хорошо. Можно переделать по аналогии с GenreDbStorage(там отлавливается EmptyResultDataAccessException в случае если данные не найдены) либо сделать вот таким способом:
![image](https://user-images.githubusercontent.com/51891976/222959493-eb33911e-147f-4669-9119-d8212ad1883b.png)

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +      checkUserExist(user.getId());
Рекомендация: Есть хитрость, благодаря которой необязательно делать запрос на exists: Метод update у jdbcTemplate возвращает число, это число означает сколько запией в БД обновилось. Если это значение > 0 значит все окей, а иначе, такой записи в БД нет и можно выкидывать NotFoundException, таким образом мы будем делать 1 запрос вместо двух.

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                new User(
Рекомендация: Маппинг юзера также можно вынести в отдельный метод, аналогично тому, как я рекомендовал в FilmDbStorage.

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film == null) {
Рекомендация: В данном случае нет необходимости проверять на null, так как в filmStorage такая проверка уже есть.

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -            @RequestParam(value = "count", defaultValue = "10", required = false) Integer count) {
А почему было исправлено на `` @GetMapping({"/popular?count={count}", "/popular"})``? Раньше было в целом правильнее, с использованием ``@RequestParam`` с defaultValue.

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Рекомендация: Чтобы не писать каждый раз конструкторы для инъекции бинов можно использовать аннотацию ломбока ``@RequiredArgsConstructor``. Эта аннотация создает конструктор автоматически для всех final полей.
![image](https://user-images.githubusercontent.com/51891976/222960158-94794bb2-ed58-4c50-82c9-02babd9fb3ab.png)

2023-03-05 12:23 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> -public class ErrorHandler {
А почему данный класс был удален?

2023-03-05 12:24 UTC, ohelly commented
> Этот спринт высосал из меня все силы(

А с чем возникли сложности? Есть еще остались вопросы, то можешь обратиться в личку - постараюсь помочь.

2023-03-05 18:21 UTC, AtamasMaria commented on src/main/resources/schema.sql
> +CONSTRAINT mpa_pk PRIMARY KEY (mpa_id)
Done)

2023-03-05 18:21 UTC, AtamasMaria commented on src/main/resources/schema.sql
> +ALTER TABLE film_genres ADD CONSTRAINT IF NOT EXISTS UC_GenreLine_GenreID_FilmID UNIQUE (genre_id, film_id);
Done)

2023-03-05 18:22 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int rate;
Это поле появлялось в БД, еще это обсуждалось у нас в группе, я добавила на всякий случай) Но сейчас уже удалила

2023-03-05 18:22 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!existLike.next()) {
Убрала добавление лайков и добавила констрейнт в БД)

2023-03-05 18:23 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet sqlRowSet = jdbcTemplate.queryForRowSet(sql, userId, filmId);
Удалила)

2023-03-05 18:23 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                new User(
Сделала маппинг и для фильмов и для пользователей

2023-03-05 18:24 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (film == null) {
done)

2023-03-05 18:26 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -            @RequestParam(value = "count", defaultValue = "10", required = false) Integer count) {
Уже не помню почему меняла

2023-03-05 18:26 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> -            @RequestParam(value = "count", defaultValue = "10", required = false) Integer count) {
вернула прежний вариант

2023-03-07 16:39 UTC, ohelly requested changes
Привет! В целом исправлены почти все замечания, осталась парочка, возможно не были замечены на прошлой итерации. Также возможно не были замечены некоторые рекомендации + добавил несколько новых.

2023-03-07 16:39 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public int hashCode() {
Рекомендация: У ломбока есть прекрасная аннотация ``@EqualsAndHashCode`` :)

В ней также можно указать по какому полю сравнивать.

2023-03-07 16:39 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!existLike.next()) {
Рекомендация: Так как добавлен констрейнт и добавлен оператор ON CONFLICT DO NOTHING, то можно проверку на существование лайка удалить, таким образом сократим количество запросов в БД.

2023-03-07 16:39 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                (List<Genre>) genreService.getFilmGenres(rs.getInt("film_id")),
Необходимо исправить: Осталось замечание с прошлой проверки

> Необходимо вынести получение жанров в FilmService, то есть из него вызывать метод получения жанров, либо оставить здесь, но получать жанры только после того, как получены все фильмы. Сейчас объясню почему:
Сейчас на получение N фильмов выполняется N запросов на получение жанров, что не очень хорошо, так как нагружается БД, это необходимо делать одним запросом, независимо от того, сколько фильмов нам необходимо обогатить жанрами.
Итого: в GenreDbStorage должен быть метод, который одним запросом получает все жанры для всех необходимых фильмов. Для этого поможет оператор IN в запросе.

2023-03-07 16:39 UTC, ohelly commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public List<Film> getFilmsPopular(Integer count) {
> Необходимо исправить: Давай переработаем метод получения популярных фильмов. Сейчас в худшем случае выполняется очень много запросов - 101 строка, 102 и затем еще несколько на 111 строке. Все это можно сделать одним запросом: В текущей реализации мы достаем сначала все идентификаторы, подходящие под наше условие(98 строка), затем, для каждого из этих идентификаторов мы достаем фильм(102строка), но нам нет необходимости это делать, ведь мы можем сразу достать все фильмы, а не только их идентификаторы: ![image](https://user-images.githubusercontent.com/51891976/222958578-89f05a46-567b-466c-9f1d-f0f692596c4f.png)
> 
> Добавим join для mpa_rating: ![image](https://user-images.githubusercontent.com/51891976/222958649-792058c9-9d29-44f3-9625-e57631a1106e.png)
> 
> Далее, я так понимаю, идет добавление фильмов в результирующий список, чтобы подбить их под количество заданное запросом(count), добавляем те фильмы, у которых нет лайков. Но мы также это можем сделать одним запросом с помощью LEFT JOIN: ![image](https://user-images.githubusercontent.com/51891976/222958759-0a3fa245-8992-430c-8fcb-9652f394bede.png)
> 
> LEFT JOIN вернет нам все результаты левой таблицы(films) попадающие под условие и все лайки, которые удалось сджойнить.
> 
> ![image](https://user-images.githubusercontent.com/51891976/222958844-cf6c4dd7-cdf2-4456-a255-a0bd8c01cf6a.png)
> 
> Итого получилось следующее, мы одним запросом, достали все необходимые нам фильмы.
> 
> Подсказка по join'ам https://learndb.ru/articles/article/30

Данное замечание также остается

2023-03-07 18:00 UTC, AtamasMaria commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public int hashCode() {
Воспользовалась аннотацией

2023-03-09 17:57 UTC, ohelly approved these changes
Привет! Теперь все отлично, исправлены все замечания. Работа принята, удачи в дальнейшем обучении!

2023-03-09 20:19 UTC, merged